[package]
distribution = "2201.10.0"
org = "xlibb"
name = "sikulix"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["sikulix"] 
icon = "icon.png"
repository = "https://github.com/xlibb/module-sikulix"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib.sikulix"
artifactId = "sikulix-native"
version = "0.1.0"
path = "../native/build/libs/sikulix-native-0.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "com.sikulix"
artifactId = "sikulixapi"
version = "2.0.5"

[[platform.java17.dependency]]
groupId = "org.openpnp"
artifactId = "opencv"
version = "4.3.0-3"

[[platform.java17.dependency]]
groupId = "net.java.dev.jna"
artifactId = "jna-platform"
version = "5.6.0"

[[platform.java17.dependency]]
groupId = "net.java.dev.jna"
artifactId = "jna"
version = "5.6.0"

[[platform.java17.dependency]]
groupId = "net.sourceforge.tess4j"
artifactId = "tess4j"
version = "4.5.4"

[[platform.java17.dependency]]
groupId = "com.github.jai-imageio"
artifactId = "jai-imageio-core"
version = "1.4.0"

[[platform.java17.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.8.0"

[[platform.java17.dependency]]
groupId = "net.sourceforge.lept4j"
artifactId = "lept4j"
version = "1.13.2"
